/**
 * TM-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatusEntity } from './statusEntity';


export interface ConductorEntity { 
    id?: number;
    firstName: string;
    lastName: string;
    cin: string;
    drivingLicence: string;
    phoneNumber: string;
    plateNumber: string;
    zone: string;
    userInformation: string;
    status?: StatusEntity;
    creationDate?: string;
    lastModifiedDate?: string;
}

