/**
 * TM-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FederatedIdentityRepresentation { 
    identityProvider?: string;
    userId?: string;
    userName?: string;
}

