/**
 * TM-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConductorEntity } from './conductorEntity';
import { StatusEntity } from './statusEntity';


export interface MotocycleEntity { 
    id?: number;
    typesOfMotocycle: string;
    brands: string;
    plateNumber: string;
    conductorEntity?: ConductorEntity;
    picture?: string;
    status?: StatusEntity;
    creationDate?: string;
    lastModifiedDate?: string;
}

