/**
 * TM-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReferencesEntity } from './referencesEntity';
import { RaceEntity } from './raceEntity';
import { StatusEntity } from './statusEntity';


export interface PayementEntity { 
    id?: number;
    race?: RaceEntity;
    methods: string;
    amount: number;
    dateTimePayement: string;
    referencesEntity?: ReferencesEntity;
    status?: StatusEntity;
    creationDate?: string;
    lastModifiedDate?: string;
}

