/**
 * TM-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClientEntity } from './clientEntity';
import { SecurityEntity } from './securityEntity';
import { ConductorEntity } from './conductorEntity';
import { StatusEntity } from './statusEntity';
import { EndingPointEntity } from './endingPointEntity';
import { StartingPointEntity } from './startingPointEntity';


export interface RaceEntity { 
    id?: number;
    client?: ClientEntity;
    conductor?: ConductorEntity;
    dateTimeDeparture?: string;
    dateTimeArrival?: string;
    distance?: number;
    price?: number;
    status?: StatusEntity;
    startingPointEntity?: StartingPointEntity;
    endingPointEntity?: EndingPointEntity;
    securityEntity?: SecurityEntity;
    creationDate?: string;
    lastModifiedDate?: string;
}

