/**
 * TM-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatusEntity } from './statusEntity';


export interface TypesRateManagementEntity { 
    id?: number;
    types: string;
    status?: StatusEntity;
    creationDate?: string;
    lastModifiedDate?: string;
}

