/**
 * TM-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserProfileAttributeMetadata } from './userProfileAttributeMetadata';
import { UserProfileAttributeGroupMetadata } from './userProfileAttributeGroupMetadata';


export interface UserProfileMetadata { 
    attributes?: Array<UserProfileAttributeMetadata>;
    groups?: Array<UserProfileAttributeGroupMetadata>;
}

