/**
 * TM-service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserProfileAttributeMetadata { 
    name?: string;
    displayName?: string;
    required?: boolean;
    readOnly?: boolean;
    annotations?: { [key: string]: object; };
    validators?: { [key: string]: { [key: string]: object; }; };
    group?: string;
    multivalued?: boolean;
}

