export * from './clientController.service';
import { ClientControllerService } from './clientController.service';
export * from './conductorController.service';
import { ConductorControllerService } from './conductorController.service';
export * from './coordinationsController.service';
import { CoordinationsControllerService } from './coordinationsController.service';
export * from './motocycleController.service';
import { MotocycleControllerService } from './motocycleController.service';
export * from './payementController.service';
import { PayementControllerService } from './payementController.service';
export * from './raceController.service';
import { RaceControllerService } from './raceController.service';
export * from './rateManagementController.service';
import { RateManagementControllerService } from './rateManagementController.service';
export * from './referencesController.service';
import { ReferencesControllerService } from './referencesController.service';
export * from './securityController.service';
import { SecurityControllerService } from './securityController.service';
export * from './securityRestController.service';
import { SecurityRestControllerService } from './securityRestController.service';
export * from './testControllerBase.service';
import { TestControllerBaseService } from './testControllerBase.service';
export * from './typesRateManagementController.service';
import { TypesRateManagementControllerService } from './typesRateManagementController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export * from './zoneController.service';
import { ZoneControllerService } from './zoneController.service';
export const APIS = [ClientControllerService, ConductorControllerService, CoordinationsControllerService, MotocycleControllerService, PayementControllerService, RaceControllerService, RateManagementControllerService, ReferencesControllerService, SecurityControllerService, SecurityRestControllerService, TestControllerBaseService, TypesRateManagementControllerService, UserControllerService, ZoneControllerService];
